### PR TITLE
Fixup cmd build

### PR DESCRIPTION
**Pull request by philips**
When first trying to get doozer running to play around with it I got really confused on how to build the doozer client from the git directory. This tries to simplify that process and make it follow go norms by moving that code into the src/ directory.

Also it adds a convenience make target so that people can quickly get started from git.

I can provide a follow on PR that creates a symlink from cmd/ to src/util/ so that the old `go get` instructions still work.

### CODE REVIEW

**Comment by dgryski** [comment]
If you're updating the build process, doesn't it make sense to update the docs at the same time?

**Comment by philips** [comment]
@dgryski I don't understand what you mean. What docs did I fail to update? I added docs in ed70cef

**Comment by dgryski** [comment]
Oh, I meant your comment about needing the symlink.  It would probably be better to simply update the docs so that they _only_ have a 'go get' command that works.

**Comment by philips** [comment]
@dgryski I did update the README to the new path in 8b61437.

I offered to add the symlink in a separate PR in case maintaing the old `go get github.com/ha/doozer/cmd/doozer` URL was important (I personally think it isn't).

**Comment by dgryski** [comment]
Ah, I misunderstood where the 'old go get' instructions were.

**Comment by kr** [comment]
If you're trying to follow Go norms, it's almost always wrong
to have a directory named `src` inside a git repo.

**Comment by philips** [comment]
@kr Hrm, you are right. I will close this PR and open something that just fixes the Makefile.

Usually for my own projects I have a separate repo for commands vs API libraries.

**Comment by philips** [comment]
@kr Thinking about this more it seems like cmd/doozer should be its own repo. It seems a odd that in order to start hacking around with the doozer client I need to:
1. git clone github.com/ha/doozer
2. cd cmd/doozer
3. go get (which fetches github.com/ha/doozer again to put it in my workspace)
4. go build
5. Start hacking

Maybe I am missing a go convention for solving this problem.

**Comment by philips** [comment]
This is what I was thinking: https://github.com/philips/doozer

Anyways it is a minor thing, just something I ran into as I started investigating doozer.

**Comment by kr** [comment]
If this repo is made properly go-gettable, it should suffice to do:

```
go get github.com/ha/doozer/...
```

and start hacking. Same goes for doozerd.

**Comment by philips** [comment]
@kr Ah! Perfect. Thanks.

**Pull request closed without merging**
