### PR TITLE
New cli command -- getr: return a body and rev

### PR DESCRIPTION
**Pull request by cespare**
Introduces the `getr` command to print the body, length, and rev for a path to avoid changing the existing get command.

The format is similar to `watch`/`wait`.

Example:

```
$ doozer getr /message
/message 3404 5
asdf

```

### CODE REVIEW

**Comment by mreiferson** [comment]
I actually think that it's a bug that the CLI `GET` does not return `rev` because the `GET` command in the client library _does_.

I think they should mirror each other.  Now is the time to correct these inconsistencies rather than adding new commands to maintain backwards compatibility.

I'll let others chime in but my vote is for updating command line get instead of adding this new command.

**Comment by mreiferson** [comment]
specifically I'm in favor of merging an _updated_ #3

**Comment by cespare** [comment]
I like changing the behavior of `get` more as well. There are some comments on #3 that are against changing `get`'s behavior, which is why I made a new command. @bketelsen, what are your objections?

**Comment by bketelsen** [comment]
@cespare none, really, other than breaking an existing API.  But we're at the right time to do that if it needs to be done.

**Comment by mreiferson** [comment]
@cespare want to update this patch to modify `GET`?

**Comment by dgryski** [comment]
For the instances where the command-line client is being called from a shell script, it should continue to be "easy" to get _only_ the value.  I don't care about breaking existing scripts, but the fix should be obvious.  I agree that this is the time to be doing it if it needs to be done.

**Comment by cespare** [comment]
@mreiferson sure, as soon as we get consensus.

@dgryski how about

```
doozer get /foobar | tail -n +2
```

? :D

Alternatives:
1. Keep two separate commands, like this pull request currently has.
2. There are references in the documentation to command-specific flags, but this is misleading as the mechanism doesn't exist (see #29). We could implement it, though.
3. We could use the global `-r` flag to control this behavior, as originally suggested by @bmizerany over in #3. That actually seems like a pretty good compromise.

**Comment by mreiferson** [comment]
I'm fine with the use of `tail -n +2`.  It certainly isn't sexy but it is consistent.

I guess part of my thinking is that I'm curious as to how the CLI client is actually used.  Is it a debugging or exploratory tool?   Something used in a more production like context?  If it's the latter it could be argued that going in this direction is a bit too ugly.

Thoughts?

**Comment by cespare** [comment]
Personally, I see the CLI tool as an exploratory tool to augment the web view, and I wouldn't really see ever using it a production context. I don't have a sense of how other people are using it, though. Is it worth asking on the mailing list?

@mreiferson thoughts about alternative no. 3?

**Comment by mreiferson** [comment]
@cespare agreed, which is why I'm fine with updating `GET` to return rev and suggesting the use of `| tail -n +2`.  In the debugging context it's easier to have one command that returns all the info rather than 2.

I think option 3 is a bit confusing.  The `-r` flag is intended to _specify_ a revision (which #3 also added to `GET`). It would seem odd and inconsistent for it to be used here to mean _receiving_ a rev in the response.  Relatedly, we probably should add `-r` support for _specifying_ the revision here (but I think the response should _always_ contain the rev).

**Comment by srid** [comment]
> There are references in the documentation to command-specific flags, but this is misleading as the mechanism doesn't exist (see #29). We could implement it, though.

+1 on implementing it ... and what about returning the data as JSON:

```
$ doozer get --json /foobar
{"key": "/foobar", "value": "hello world", "rev": 1234}
$
```

JSON makes sense if we want to print further metadata such as the `ephemeral` (or `create-mode`) flag for keys that were created as [ephemeral](https://github.com/ha/doozerd/issues/52).

> doozer get /foobar | tail -n +2

-0 ... i'd prefer to keep it simple. i can understand why `watch` or `wait` would print revisions, but for `get` it seems superfluous to do it by default.

> I guess part of my thinking is that I'm curious as to how the CLI client is actually used.

for most part, we directly use the doozer client API (via Go or Ruby) - but for quick and dirty scripting needs, the command-line client proves to be sufficient. for example:

```
ENDPOINT=$(doozer -a `cat /s/etc/doozer/doozer_uri` get /cluster/config/endpoint)
```

**Comment by mreiferson** [comment]
@srid makes a good point w/r/t being used in quick bash scripts, etc.

To that end, we do already have the `STAT` command to get the revision of a path.  Is there _really_ a strong need to have one command that does both when we already have two well named commands that do them separately?

Perhaps the only thing that needs to happen is to add `-r` support to `GET` so that you can _specify_ a revision?

In the future, when ha/doozerd#52 lands, we can update `STAT` to return more metadata.

**Comment by cespare** [comment]
@mreiferson well, if you get the contents and revision separately, there's no guarantee that the data actually corresponds to the revision. If you want those to be consistent, there needs to be a single command.

**Comment by mreiferson** [comment]
thats why we should add `-r` support so that you can get the revision first then get the contents for that revision

**Pull request closed without merging**
