### PR TITLE
cleanup and compilation

### PR DESCRIPTION
**Pull request by mreiferson**
goprotobuf changes and fixes so that it compiles cc @ha

### CODE REVIEW

**Comment by mreiferson** [comment]
heads up, don't merge this yet I'd like to do a bit of testing and validation.

also, this commit is from a few months ago and it seems there might have been more changes to `goprotobuf` in the meantime.

will comment when it's ready.

**Comment by mreiferson** [comment]
ok, all tests are passing in ha/doozerd#49 (that uses this changeset) so I think this should go in first.

RFR @bketelsen

**Comment by bketelsen** [comment]
LGT<

**Comment by bketelsen** [comment]
Me

**Pull request merged**
