### PR TITLE
Add revision support to get cli command

### PR DESCRIPTION
**Pull request by mloughran**
I was playing around with the doozer client as a way of getting a feel for solving some problems with Doozer, and was surprised that get did not return the revision. I added this feature to the client. Since that was so easy, I also made another commit to allow passing a revision to get. You might not want the second commit in it's current form though - I wasn't sure how to make the revision argument optional. Cheers!

### CODE REVIEW

**Comment by mreiferson** [comment]
this seems like something still worth implementing... will let others chime in

**Comment by bketelsen** [comment]
this does look interesting, but we shouldn't change the default behavior of the get.

**Comment by dgryski** [comment]
Easy enough to add a new command though -- v(ersioned)get for example.

**Comment by bketelsen** [comment]
agreed, if the patch is modified to be a new command, i think it's much more useful.

**Comment by cespare** [comment]
Implemented a new command for returning both body and rev as `getr` over in #31.

**Comment by mreiferson** [comment]
superseded by #31

**Pull request closed without merging**
